# Form implementation generated from reading ui file 'client.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_client(object):
    def setupUi(self, dialog_client):
        dialog_client.setObjectName("dialog_client")
        dialog_client.setGeometry(QtCore.QRect(0, 0, 200, 215))
        dialog_client.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(dialog_client)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_key = QtWidgets.QPushButton(parent=dialog_client)
        self.btn_key.setObjectName("btn_key")
        self.gridLayout.addWidget(self.btn_key, 3, 0, 1, 1)
        self.btn_cap = QtWidgets.QPushButton(parent=dialog_client)
        self.btn_cap.setObjectName("btn_cap")
        self.gridLayout.addWidget(self.btn_cap, 5, 0, 1, 1)
        self.btn_exit = QtWidgets.QPushButton(parent=dialog_client)
        self.btn_exit.setObjectName("btn_exit")
        self.gridLayout.addWidget(self.btn_exit, 8, 0, 1, 1)
        self.btn_shutdown = QtWidgets.QPushButton(parent=dialog_client)
        self.btn_shutdown.setObjectName("btn_shutdown")
        self.gridLayout.addWidget(self.btn_shutdown, 7, 0, 1, 1)
        self.btn_display = QtWidgets.QPushButton(parent=dialog_client)
        self.btn_display.setObjectName("btn_display")
        self.gridLayout.addWidget(self.btn_display, 6, 0, 1, 1)
        self.btn_app = QtWidgets.QPushButton(parent=dialog_client)
        self.btn_app.setObjectName("btn_app")
        self.gridLayout.addWidget(self.btn_app, 2, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(parent=dialog_client)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.btn_connect = QtWidgets.QPushButton(parent=dialog_client)
        self.btn_connect.setObjectName("btn_connect")
        self.horizontalLayout.addWidget(self.btn_connect)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(parent=dialog_client)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(dialog_client)
        QtCore.QMetaObject.connectSlotsByName(dialog_client)

    def retranslateUi(self, dialog_client):
        _translate = QtCore.QCoreApplication.translate
        dialog_client.setWindowTitle(_translate("Dialog_client", "Dialog"))
        self.btn_key.setText(_translate("Dialog_client", "Keystroke"))
        self.btn_cap.setText(_translate("Dialog_client", "Screenshot"))
        self.btn_exit.setText(_translate("Dialog_client", "Exit"))
        self.btn_shutdown.setText(_translate("Dialog_client", "Shutdow"))
        self.btn_display.setText(_translate("Dialog_client", "Display"))
        self.btn_app.setText(_translate("Dialog_client", "App running"))
        self.btn_connect.setText(_translate("Dialog_client", "Connect"))
        self.label.setText(_translate("Dialog_client", "No Connection"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog_client = QtWidgets.QDialog()
    ui = Ui_Dialog_client()
    ui.setupUi(dialog_client)
    dialog_client.show()
    sys.exit(app.exec())
