# Form implementation generated from reading ui file 'display_tmp.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_thread(object):
    def setupUi(self, dialog_capture):
        dialog_capture.setObjectName("dialog_capture")
        dialog_capture.setGeometry(QtCore.QRect(0, 0, 936, 564))
        self.pushButton_2 = QtWidgets.QPushButton(parent=dialog_capture)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 520, 261, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(parent=dialog_capture)
        self.pushButton.setGeometry(QtCore.QRect(510, 520, 251, 31))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=dialog_capture)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 911, 481))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(parent=self.horizontalLayoutWidget)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)

        self.retranslateUi(dialog_capture)
        QtCore.QMetaObject.connectSlotsByName(dialog_capture)

    def retranslateUi(self, dialog_capture):
        _translate = QtCore.QCoreApplication.translate
        dialog_capture.setWindowTitle(_translate("Dialog_thread", "Dialog"))
        self.pushButton_2.setText(_translate("Dialog_thread", "Capture thread"))
        self.pushButton.setText(_translate("Dialog_thread", "Ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog_capture = QtWidgets.QDialog()
    ui = Ui_Dialog_thread()
    ui.setupUi(dialog_capture)
    dialog_capture.show()
    sys.exit(app.exec())
