# Form implementation generated from reading ui file 'file.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_file(object):
    def setupUi(self, dialog_file):
        dialog_file.setObjectName("dialog_file")
        dialog_file.setGeometry(QtCore.QRect(0, 0, 452, 271))
        self.groupBox = QtWidgets.QGroupBox(parent=dialog_file)
        self.groupBox.setGeometry(QtCore.QRect(10, 60, 424, 321))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.widget = QtWidgets.QWidget(parent=self.groupBox)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_send = QtWidgets.QPushButton(parent=self.widget)
        self.btn_send.setObjectName("btn_send")
        self.horizontalLayout_3.addWidget(self.btn_send)
        self.btn_rev = QtWidgets.QPushButton(parent=self.widget)
        self.btn_rev.setObjectName("btn_rev")
        self.horizontalLayout_3.addWidget(self.btn_rev)
        self.verticalLayout.addWidget(self.widget)
        self.layoutWidget = QtWidgets.QWidget(parent=dialog_file)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 431, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.btn_browser = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btn_browser.setObjectName("btn_browser")
        self.horizontalLayout.addWidget(self.btn_browser)

        self.retranslateUi(dialog_file)
        QtCore.QMetaObject.connectSlotsByName(dialog_file)

    def retranslateUi(self, dialog_file):
        _translate = QtCore.QCoreApplication.translate
        dialog_file.setWindowTitle(_translate("Dialog_file", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog_file", "Server address"))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog_file", "path"))
        self.btn_send.setText(_translate("Dialog_file", "Send"))
        self.btn_rev.setText(_translate("Dialog_file", "Receive "))
        self.btn_browser.setText(_translate("Dialog_file", "Client address "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog_file = QtWidgets.QDialog()
    ui = Ui_Dialog_file()
    ui.setupUi(dialog_file)
    dialog_file.show()
    sys.exit(app.exec())
