# Form implementation generated from reading ui file 'start.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_start(object):
    def setupUi(self, dialog_start):
        dialog_start.setObjectName("dialog_start")
        dialog_start.setGeometry(QtCore.QRect(0, 0, 374, 50))
        self.layoutWidget = QtWidgets.QWidget(parent=dialog_start)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 353, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.btn_start = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btn_start.setObjectName("btn_start")
        self.horizontalLayout_2.addWidget(self.btn_start)

        self.retranslateUi(dialog_start)
        QtCore.QMetaObject.connectSlotsByName(dialog_start)

    def retranslateUi(self, dialog_start):
        _translate = QtCore.QCoreApplication.translate
        dialog_start.setWindowTitle(_translate("Dialog_start", "Dialog"))
        self.btn_start.setText(_translate("Dialog_start", "Start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog_start = QtWidgets.QDialog()
    ui = Ui_Dialog_start()
    ui.setupUi(dialog_start)
    dialog_start.show()
    sys.exit(app.exec())
