# Form implementation generated from reading ui file 'server.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_server(object):
    def setupUi(self, dialog_server):
        dialog_server.setObjectName("dialog_server")
        dialog_server.setGeometry(QtCore.QRect(0, 0, 300, 165))
        self.label = QtWidgets.QLabel(parent=dialog_server)
        self.label.setGeometry(QtCore.QRect(120, -10, 131, 71))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(parent=dialog_server)
        self.pushButton.setGeometry(QtCore.QRect(70, 40, 151, 81))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(dialog_server)
        QtCore.QMetaObject.connectSlotsByName(dialog_server)

    def retranslateUi(self, dialog_server):
        _translate = QtCore.QCoreApplication.translate
        dialog_server.setWindowTitle(_translate("Dialog_server", "Server"))
        self.label.setText(_translate("Dialog_server", "Server<3"))
        self.pushButton.setText(_translate("Dialog_server", "Start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog_server = QtWidgets.QDialog()
    ui = Ui_Dialog_server()
    ui.setupUi(dialog_server)
    dialog_server.show()
    sys.exit(app.exec())
